language: scala
sudo: false
scala:
- 2.11.12
- 2.12.6
jdk: oraclejdk8
script:
- sbt scalafmtSbtCheck scalafmtCheck test:scalafmtCheck "++ ${TRAVIS_SCALA_VERSION}! -v" test
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/launchers
before_cache:
- find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm
- find $HOME/.ivy2/cache -name "*SNAPSHOT*" | xargs rm -rf
