name: CI
on:
  pull_request:
  push:
  schedule:
  - cron: '0 20 * * 5'
jobs:
  test:
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        java:
          - 8
          - 11
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@de1bb2b0c5634f0fc4438d7aa9944e68f9bf86cc # v3.6.0
      with:
        java-version: ${{matrix.java}}
        distribution: temurin
    - uses: coursier/cache-action@v6
    - shell: bash
      run: sbt -v
           "+ scalafmtCheckAll"
           scalafmtSbtCheck
           "+ test"
